<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTlgezh2\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTlgezh2/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerTlgezh2.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerTlgezh2\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerTlgezh2\App_KernelProdContainer([
    'container.build_hash' => 'Tlgezh2',
    'container.build_id' => '7570e765',
    'container.build_time' => 1706014419,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTlgezh2');
