<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_admin' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], [], []],
    'app_default' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/']], [], [], []],
    'app_order' => [[], ['_controller' => 'App\\Controller\\OrderController::order'], [], [['text', '/bestelling']], [], [], []],
    'app_order_history' => [[], ['_controller' => 'App\\Controller\\OrderHistoryController::index'], [], [['text', '/bestellingen']], [], [], []],
    'app_registration' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/registration']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
];
