<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Order extends \App\Entity\Order implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'address' => [parent::class, 'address', null],
        "\0".parent::class."\0".'comment' => [parent::class, 'comment', null],
        "\0".parent::class."\0".'date' => [parent::class, 'date', null],
        "\0".parent::class."\0".'deliveryOption' => [parent::class, 'deliveryOption', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'orderItems' => [parent::class, 'orderItems', null],
        "\0".parent::class."\0".'ordered_at' => [parent::class, 'ordered_at', null],
        "\0".parent::class."\0".'phoneNr' => [parent::class, 'phoneNr', null],
        "\0".parent::class."\0".'time' => [parent::class, 'time', null],
        "\0".parent::class."\0".'username' => [parent::class, 'username', null],
        'address' => [parent::class, 'address', null],
        'comment' => [parent::class, 'comment', null],
        'date' => [parent::class, 'date', null],
        'deliveryOption' => [parent::class, 'deliveryOption', null],
        'email' => [parent::class, 'email', null],
        'id' => [parent::class, 'id', null],
        'name' => [parent::class, 'name', null],
        'orderItems' => [parent::class, 'orderItems', null],
        'ordered_at' => [parent::class, 'ordered_at', null],
        'phoneNr' => [parent::class, 'phoneNr', null],
        'time' => [parent::class, 'time', null],
        'username' => [parent::class, 'username', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
